//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class SKSEntities : DbContext
{
    public SKSEntities()
        : base("name=SKSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tbl_BillDetails> tbl_BillDetails { get; set; }
    public virtual DbSet<tbl_CompanyMaster> tbl_CompanyMaster { get; set; }
    public virtual DbSet<tbl_ProductMaster> tbl_ProductMaster { get; set; }
    public virtual DbSet<tbl_ProductPrice> tbl_ProductPrice { get; set; }
    public virtual DbSet<tbl_BillDetails_Other> tbl_BillDetails_Other { get; set; }
    public virtual DbSet<tbl_BillDetails_temp> tbl_BillDetails_temp { get; set; }
    public virtual DbSet<tbl_CustomerBillingAddress> tbl_CustomerBillingAddress { get; set; }
    public virtual DbSet<tbl_CustomerShippingAddress> tbl_CustomerShippingAddress { get; set; }
    public virtual DbSet<tbl_SKSDetails> tbl_SKSDetails { get; set; }
    public virtual DbSet<tbl_StateMaster> tbl_StateMaster { get; set; }
    public virtual DbSet<vw_CompanyMaster> vw_CompanyMaster { get; set; }
    public virtual DbSet<vw_ProductMaster> vw_ProductMaster { get; set; }
    public virtual DbSet<vw_ProductPrice> vw_ProductPrice { get; set; }
    public virtual DbSet<vw_BillingCustomer> vw_BillingCustomer { get; set; }
    public virtual DbSet<vw_ShippingCustomer> vw_ShippingCustomer { get; set; }
    public virtual DbSet<tbl_TransportationMaster> tbl_TransportationMaster { get; set; }
    public virtual DbSet<tbl_BillMaster> tbl_BillMaster { get; set; }
    public virtual DbSet<vw_Bill_InvoiceDetails> vw_Bill_InvoiceDetails { get; set; }
    public virtual DbSet<vw_BillInvoiceMaster> vw_BillInvoiceMaster { get; set; }
    public virtual DbSet<tbl_ProductPriceChangesLog> tbl_ProductPriceChangesLog { get; set; }
    public virtual DbSet<tbl_Users> tbl_Users { get; set; }

    public virtual ObjectResult<getInvoiceDetail_Result> getInvoiceDetail(Nullable<long> invoiceNo, Nullable<int> pagingsize, Nullable<int> pageno)
    {
        var invoiceNoParameter = invoiceNo.HasValue ?
            new ObjectParameter("InvoiceNo", invoiceNo) :
            new ObjectParameter("InvoiceNo", typeof(long));

        var pagingsizeParameter = pagingsize.HasValue ?
            new ObjectParameter("pagingsize", pagingsize) :
            new ObjectParameter("pagingsize", typeof(int));

        var pagenoParameter = pageno.HasValue ?
            new ObjectParameter("pageno", pageno) :
            new ObjectParameter("pageno", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInvoiceDetail_Result>("getInvoiceDetail", invoiceNoParameter, pagingsizeParameter, pagenoParameter);
    }
}
