//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CSDBEntities : DbContext
{
    public CSDBEntities()
        : base("name=CSDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tbl_ContactUS> tbl_ContactUS { get; set; }
    public virtual DbSet<tbl_ContactUS_Revert> tbl_ContactUS_Revert { get; set; }
    public virtual DbSet<vw_ContactUs> vw_ContactUs { get; set; }
}
