//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVSite_Admin.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactUS_Revert
    {
        public long Id { get; set; }
        public long ContactUsId { get; set; }
        public string BusinessMessageReplied { get; set; }
        public Nullable<System.DateTime> ReplySentOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbl_ContactUS tbl_ContactUS { get; set; }
    }
}
